apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-timing-react-vibe

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      platform.intility.no/app: timing-react-vibe
      app.kubernetes.io/managed-by: argocd

resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - networkpolicy.yaml
  - resourcequota.yaml

images:
  - name: app
    newName: ghcr.io/intility/timing-react-vibe
    newTag: sha-d27a35c
